# Generated by Django 5.1.3 on 2024-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('agent', 'Agent')], default='Customer', max_length=10),
        ),
    ]
