# Generated by Django 5.1.3 on 2024-11-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='company_contact',
            field=models.CharField(default=6285156579635, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='company_email',
            field=models.EmailField(default='sumberMakmur@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
