# Generated by Django 5.1 on 2024-11-29 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='npwp',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='agentapplication',
            name='npwp',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16, message='NPWP must be exactly 16 characters.')]),
        ),
    ]
