# Generated by Django 5.1 on 2024-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_customuser_npwp_alter_agentapplication_npwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_picture/'),
        ),
    ]
