# Generated by Django 5.1.3 on 2024-11-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_agentapplication_company_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_email',
        ),
    ]
