# Generated by Django 5.1.3 on 2024-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_customuser_company_contact_customuser_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
